averages:
  - name: "medicamentos"
    criteria: "precios"
    columns:
      - "Ticket de medicamentos - general. FONASA"
      - "Ticket de medicamentos - general. NO FONASA"
      - "Ticket de medicamentos topeados- antihipertensivos (valsartán, amlodipina, hidroclorotiazida, enalapril). FONASA"
      - "Ticket de medicamentos topeados- antihipertensivos (valsartán, amlodipina, hidroclorotiazida, enalapril). NO FONASA"
  - name: "tickets"
    criteria: "precios"
    columns:
      - "Consulta no urgente consultorio - medicina general. FONASA"
      - "Consulta no urgente consultorio - medicina general. NO FONASA"
      - "Consulta no urgente consultorio - pediatria. FONASA"
      - "Consulta no urgente consultorio - pediatria. NO FONASA"
      - "Consulta no urgente consultorio - gineco-obstetricia (control de embarazo). FONASA"
      - "Consulta no urgente consultorio - gineco-obstetricia (control de embarazo). NO FONASA"
      - "Consulta no urgente consultorio - ginecologia. FONASA"
      - "Consulta no urgente consultorio - ginecologia. NO FONASA"
      - "Consulta no urgente consultorio - otras especialidades. FONASA"
      - "Consulta no urgente consultorio - otras especialidades. NO FONASA"
      - "Consulta no urgencia domicilio. FONASA"
      - "Consulta no urgencia domicilio. NO FONASA"
      - "Consulta odontologica. FONASA"
      - "Consulta odontologica. NO FONASA"
      - "Consulta medico de referencia. FONASA"
      - "Consulta medico de referencia. NO FONASA"
  - name: "tickets_urgentes"
    criteria: "precios"
    columns:
      - "Consulta urgencia centralizada. FONASA"
      - "Consulta urgencia centralizada. NO FONASA"
      - "Consulta urgencia domicilio. FONASA"
      - "Consulta urgencia domicilio. NO FONASA"
  - name: "estudios"
    criteria: "precios"
    columns:
      - "Endoscopía digestiva. Endoscopia esofagogastroduodenal. FONASA"
      - "Endoscopía digestiva. Endoscopia esofagogastroduodenal. NO FONASA"
      - "Ecografía simple. FONASA"
      - "Ecografía simple. NO FONASA"
      - "Ecodoppler miembros (inferiores / superiores) arterial / venoso. FONASA"
      - "Ecodoppler miembros (inferiores / superiores) arterial / venoso. NO FONASA"
      - "Rx abdomen / aparato urinario simple. FONASA"
      - "Rx abdomen / aparato urinario simple. NO FONASA"
      - "Rx torax. FONASA"
      - "Rx torax. NO FONASA"
      - "Rx colorectal. (c/contraste) FONASA"
      - "Rx colorectal. (c/contraste) NO FONASA"
      - "Resonancia nuclear magnética, una región. FONASA"
      - "Resonancia nuclear magnética, una región. NO FONASA"
      - "Tomografía axial computarizada, una región. FONASA"
      - "Tomografía axial computarizada, una región. NO FONASA"
      - "Laboratorio, rutina básica. FONASA"
      - "Laboratorio, rutina básica. NO FONASA"
